name: Discord Notifications

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: "˗ˏˋ a pull request was made ´ˎ˗"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_NOTIFS }}
