name: Automation

on:
  pull_request:
    types: [opened]
  issues:
    types: [closed]

jobs:
  update-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI with PAT
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      # pull request opened (move to Review)
      - name: Add PR to project and move to Review
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          # Get the project ID for your v2 board
          PROJECT_ID=$(gh api graphql -f query='
            query {
              user(login: "NoxAstrica") {
                projectV2(number: 1) {
                  id
                }
              }
            }' --jq '.data.user.projectV2.id')

          # Get the field ID for the "Status" field
          STATUS_FIELD_ID=$(gh api graphql -f query='
            query($projectId:ID!) {
              node(id:$projectId) {
                ... on ProjectV2 {
                  fields(first:20) {
                    nodes {
                      id
                      name
                    }
                  }
                }
              }
            }' -F projectId="$PROJECT_ID" --jq '.data.node.fields.nodes[] | select(.name=="Status") | .id')

          # Create the item in the project and set Status to "Review"
          gh api graphql -f query='
            mutation($projectId:ID!, $title:String!, $contentID:ID!, $statusFieldID:ID!, $statusValue:String!) {
              addProjectV2Item(input:{projectId:$projectId, contentId:$contentID}) {
                item {
                  id
                }
              }
              updateProjectV2ItemField(input:{projectId:$projectId, itemId:$contentID, fieldId:$statusFieldID, value:$statusValue}) {
                projectV2Item {
                  id
                }
              }
            }' \
            -F projectId="$PROJECT_ID" \
            -F title="${{ github.event.pull_request.title }}" \
            -F contentID="${{ github.event.pull_request.node_id }}" \
            -F statusFieldID="$STATUS_FIELD_ID" \
            -F statusValue='{"name":"Review"}'

      # issue closed (move to Done)
      - name: Move Issue to Done
        if: github.event_name == 'issues' && github.event.action == 'closed'
        run: |
          PROJECT_ID=$(gh api graphql -f query='
            query {
              user(login: "NoxAstrica") {
                projectV2(number: 1) {
                  id
                }
              }
            }' --jq '.data.user.projectV2.id')

          STATUS_FIELD_ID=$(gh api graphql -f query='
            query($projectId:ID!) {
              node(id:$projectId) {
                ... on ProjectV2 {
                  fields(first:20) {
                    nodes {
                      id
                      name
                    }
                  }
                }
              }
            }' -F projectId="$PROJECT_ID" --jq '.data.node.fields.nodes[] | select(.name=="Status") | .id')

          gh api graphql -f query='
            mutation($projectId:ID!, $contentID:ID!, $statusFieldID:ID!, $statusValue:String!) {
              addProjectV2Item(input:{projectId:$projectId, contentId:$contentID}) {
                item {
                  id
                }
              }
              updateProjectV2ItemField(input:{projectId:$projectId, itemId:$contentID, fieldId:$statusFieldID, value:$statusValue}) {
                projectV2Item {
                  id
                }
              }
            }' \
            -F projectId="$PROJECT_ID" \
            -F contentID="${{ github.event.issue.node_id }}" \
            -F statusFieldID="$STATUS_FIELD_ID" \
            -F statusValue='{"name":"Done"}'
