name: Automation

on:
  pull_request:
    types: [opened]
  issues:
    types: [closed]

jobs:
  update-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI with PAT
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      # pull request opened (move to Review)
      - name: Add PR to project and move to Review
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          # Add PR as card to the "Review" column
          gh project card create \
            --project 1 \
            --owner NoxAstrica \
            --column "Review" \
            --content ${{ github.event.pull_request.html_url }}

      # issue is closed (move to Done)
      - name: Move Issue to Done
        if: github.event_name == 'issues' && github.event.action == 'closed'
        run: |
          # Find the card ID for this issue in the project
          CARD_ID=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /projects/columns/cards \
            --jq ".[] | select(.content_url==\"${{ github.event.issue.url }}\") | .id")

          if [ -z "$CARD_ID" ]; then
            echo "Issue card not found, creating a new card in 'Done' column"
            # Find Done column ID
            COLUMN_ID=$(gh api -H "Accept: application/vnd.github.v3+json" /projects/1/columns \
              --jq ".[] | select(.name==\"Done\") | .id")
            # Create new card directly in Done column
            gh project card create --column "$COLUMN_ID" --content "${{ github.event.issue.html_url }}"
          else
            # Move existing card to Done column
            COLUMN_ID=$(gh api -H "Accept: application/vnd.github.v3+json" /projects/1/columns \
              --jq ".[] | select(.name==\"Done\") | .id")
            gh api -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              /projects/columns/cards/$CARD_ID/moves \
              -f position="top" \
              -F column_id=$COLUMN_ID
          fi
