name: Fetch Project Info

on:
  workflow_dispatch:

jobs:
  fetch-project-info:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Get IDs
        run: |
          gh api graphql -f query='
          query {
            viewer {
              projectV2(number: 1) {
                id
                fields(first: 20) {
                  nodes {
                    __typename
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options { id name }
                    }
                  }
                }
              }
            }
          }'
