name: Get Project ID

on:
  push:
    branches: [ main ]

jobs:
  fetch-project-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Project ID
        uses: monry/actions-get-project-id@v2
        with:
          github-token: ${{ secrets.GH_PAT }}
          project-owner: 'NoxAstrica'
          project-number: 1
