wait how do I update 

name: Get Project ID

on:
  push:
    branches: [ main ]

jobs:
  fetch-project-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get Project ID
        id: get_project
        uses: monry/actions-get-project-id@v2
        with:
          github-token: ${{ secrets.GH_PAT }}
          project-owner: 'NoxAstrica'
          project-number: 1

      - name: Show Project ID
        run: echo "Project ID is ${{ steps.get_project.outputs.project-id }}"

to also see statys field id and option id? SEPARATE CODE FROM THIS ONE. ALSO USE SIMPLE METHODS
